name: armTemplateDeployment

on:
  push:
    branches:
      - master
      
  workflow_dispatch:

jobs:
  armDeploy:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Resource Group
        uses: Azure/cli@1.0.4
        with:
          inlinescript: |
            az deployment sub create --location "West Europe" --template-file ./arm-templates/resourcegroup.json



